name = "MultivariateBases"
uuid = "be282fd4-ad43-11e9-1d11-8bd9d7e43378"
repo = "https://github.com/JuliaAlgebra/MultivariateBases.jl.git"
version = "0.2.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
MutableArithmetics = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"
StarAlgebras = "0c0c59c1-dc5f-42e9-9a8b-b5dc384a6cd1"

[compat]
MultivariatePolynomials = "0.5.3"
MutableArithmetics = "1"
julia = "1.6"
