name = "MultivariateBases"
uuid = "be282fd4-ad43-11e9-1d11-8bd9d7e43378"
repo = "https://github.com/JuliaAlgebra/MultivariateBases.jl.git"
version = "0.1.2"

[deps]
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
MutableArithmetics = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"

[compat]
MultivariatePolynomials = "0.3.5"
MutableArithmetics = "0.2.1"
julia = "1"

[extras]
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DynamicPolynomials"]
