var documenterSearchIndex = {"docs": [

{
    "location": "#",
    "page": "Introduction",
    "title": "Introduction",
    "category": "page",
    "text": "DocTestSetup = quote\n    using MultivariateBases\nend"
},

{
    "location": "#MultivariateBases.AbstractPolynomialBasis",
    "page": "Introduction",
    "title": "MultivariateBases.AbstractPolynomialBasis",
    "category": "type",
    "text": "abstract type AbstractPolynomialBasis end\n\nPolynomial basis of a subspace of the polynomials [Section~3.1.5, BPT12].\n\n[BPT12] Blekherman, G.; Parrilo, P. A. & Thomas, R. R. Semidefinite Optimization and Convex Algebraic Geometry. Society for Industrial and Applied Mathematics, 2012.\n\n\n\n\n\n"
},

{
    "location": "#MultivariateBases.maxdegree_basis",
    "page": "Introduction",
    "title": "MultivariateBases.maxdegree_basis",
    "category": "function",
    "text": "maxdegree_basis(B::Type{<:AbstractPolynomialBasis}, variables, maxdegree::Int)\n\nReturn the basis of type B generating all polynomials of degree up to maxdegree with variables variables.\n\n\n\n\n\n"
},

{
    "location": "#MultivariateBases.basis_covering_monomials",
    "page": "Introduction",
    "title": "MultivariateBases.basis_covering_monomials",
    "category": "function",
    "text": "basis_covering_monomials(B::Type{<:AbstractPolynomialBasis}, monos::AbstractVector{<:AbstractMonomial})\n\nReturn the minimal basis of type B that can generate all polynomials of the monomial basis generated by monos.\n\nExamples\n\nFor example, to generate all the polynomials with nonzero coefficients for the monomials x^4 and x^2, we need three polynomials as otherwise, we generate polynomials with nonzero constant term.\n\njulia> using DynamicPolynomials\n\njulia> @polyvar x\n(x,)\n\njulia> basis_covering_monomials(ChebyshevBasis, [x^4, x^2])\nChebyshevBasisFirstKind{Polynomial{true,Float64}}(DynamicPolynomials.Polynomial{true,Float64}[8.0x⁴ - 8.0x² + 1.0, 2.0x² - 1.0, 1.0])\n\n\n\n\n\n"
},

{
    "location": "#MultivariateBases.FixedPolynomialBasis",
    "page": "Introduction",
    "title": "MultivariateBases.FixedPolynomialBasis",
    "category": "type",
    "text": "struct FixedPolynomialBasis{PT<:MP.AbstractPolynomialLike, PV<:AbstractVector{PT}} <: AbstractPolynomialBasis\n    polynomials::PV\nend\n\nPolynomial basis with the polynomials of the vector polynomials. For instance, FixedPolynomialBasis([1, x, 2x^2-1, 4x^3-3x]) is the Chebyshev polynomial basis for cubic polynomials in the variable x.\n\n\n\n\n\n"
},

{
    "location": "#MultivariateBases-1",
    "page": "Introduction",
    "title": "MultivariateBases",
    "category": "section",
    "text": "MultivariateBases.jl is a standardized API for multivariate polynomial bases based on the MultivariatePolynomials API.AbstractPolynomialBasis\nmaxdegree_basis\nbasis_covering_monomials\nFixedPolynomialBasis"
},

{
    "location": "#MultivariateBases.MonomialBasis",
    "page": "Introduction",
    "title": "MultivariateBases.MonomialBasis",
    "category": "type",
    "text": "struct MonomialBasis{MT<:MP.AbstractMonomial, MV<:AbstractVector{MT}} <: AbstractPolynomialBasis\n    monomials::MV\nend\n\nMonomial basis with the monomials of the vector monomials. For instance, MonomialBasis([1, x, y, x^2, x*y, y^2]) is the monomial basis for the subspace of quadratic polynomials in the variables x, y.\n\n\n\n\n\n"
},

{
    "location": "#MultivariateBases.ScaledMonomialBasis",
    "page": "Introduction",
    "title": "MultivariateBases.ScaledMonomialBasis",
    "category": "type",
    "text": "struct ScaledMonomialBasis{MT<:MP.AbstractMonomial, MV<:AbstractVector{MT}} <: AbstractPolynomialBasis\n    monomials::MV\nend\n\nScaled monomial basis (see [Section 3.1.5, BPT12]) with the monomials of the vector monomials. Given a monomial x^alpha = x_1^alpha_1 cdots x_n^alpha_n of degree d = sum_i=1^n alpha_i, the corresponding polynomial of the basis is\n\nd choose alpha^frac12 x^alpha quad text where  quad\nd choose alpha = fracdalpha_1 alpha_2 cdots alpha_n\n\nFor instance, create a polynomial with the basis xy^2 xy creates the polynomial sqrt3 a xy^2 + sqrt2 b xy where a and b are new JuMP decision variables. Constraining the polynomial axy^2 + bxy to be zero with the scaled monomial basis constrains a/√3 and b/√2 to be zero.\n\n[BPT12] Blekherman, G.; Parrilo, P. A. & Thomas, R. R. Semidefinite Optimization and Convex Algebraic Geometry. Society for Industrial and Applied Mathematics, 2012.\n\n\n\n\n\n"
},

{
    "location": "#Monomial-basis-1",
    "page": "Introduction",
    "title": "Monomial basis",
    "category": "section",
    "text": "MonomialBasis\nScaledMonomialBasis"
},

{
    "location": "#MultivariateBases.AbstractMultipleOrthogonalBasis",
    "page": "Introduction",
    "title": "MultivariateBases.AbstractMultipleOrthogonalBasis",
    "category": "type",
    "text": "abstract type AbstractMultipleOrthogonalBasis{P} <: AbstractPolynomialVectorBasis{P, Vector{P}} end\n\nPolynomial basis such that langle p_i(x) p_j(x) rangle = 0 if i neq j where\n\nlangle p(x) q(x) rangle = int p(x)q(x) w(x) dx\n\nwhere the weight is a product of weight functions w(x) = w_1(x_1)w_2(x_2) cdots w_n(x_n) in each variable. The polynomial of the basis are product of univariate polynomials: p(x) = p_1(x_1)p_2(x_2) cdots p_n(x_n). where the univariate polynomials of variable x_i form an univariate orthogonal basis for the weight function w_i(x_i). Therefore, they satisfy the recurrence relation\n\nd_k p_k(x_i) = (a_k x_i + b_k) p_k-1(x_i) + c_k p_k-2(x_i)\n\nwhere reccurence_first_coef gives a_k, reccurence_second_coef gives b_k, reccurence_third_coef gives c_k and reccurence_deno_coef gives d_k.\n\n\n\n\n\n"
},

{
    "location": "#MultivariateBases.univariate_orthogonal_basis",
    "page": "Introduction",
    "title": "MultivariateBases.univariate_orthogonal_basis",
    "category": "function",
    "text": "univariate_orthogonal_basis(B::Type{<:AbstractMultipleOrthogonalBasis},\n                            variable::MP.AbstractVariable, degree::Integer)\n\nReturn the vector of univariate polynomials of the basis B up to degree with variable variable.\n\n\n\n\n\n"
},

{
    "location": "#MultivariateBases.reccurence_first_coef",
    "page": "Introduction",
    "title": "MultivariateBases.reccurence_first_coef",
    "category": "function",
    "text": "reccurence_first_coef(B::Type{<:AbstractMultipleOrthogonalBasis}, degree::Integer)\n\nReturn a_{degree} in recurrence equation\n\nd_k p_k(x_i) = (a_k x_i + b_k) p_k-1(x_i) + c_k p_k-2(x_i)\n\n\n\n\n\n"
},

{
    "location": "#MultivariateBases.reccurence_second_coef",
    "page": "Introduction",
    "title": "MultivariateBases.reccurence_second_coef",
    "category": "function",
    "text": "reccurence_second_coef(B::Type{<:AbstractMultipleOrthogonalBasis}, degree::Integer)\n\nReturn b_{degree} in recurrence equation\n\nd_k p_k(x_i) = (a_k x_i + b_k) p_k-1(x_i) + c_k p_k-2(x_i)\n\n\n\n\n\n"
},

{
    "location": "#MultivariateBases.reccurence_third_coef",
    "page": "Introduction",
    "title": "MultivariateBases.reccurence_third_coef",
    "category": "function",
    "text": "reccurence_third_coef(B::Type{<:AbstractMultipleOrthogonalBasis}, degree::Integer)\n\nReturn c_{degree} in recurrence equation\n\nd_k p_k(x_i) = (a_k x_i + b_k) p_k-1(x_i) + c_k p_k-2(x_i)\n\n\n\n\n\n"
},

{
    "location": "#MultivariateBases.reccurence_deno_coef",
    "page": "Introduction",
    "title": "MultivariateBases.reccurence_deno_coef",
    "category": "function",
    "text": "reccurence_deno_coef(B::Type{<:AbstractMultipleOrthogonalBasis}, degree::Integer)\n\nReturn d_{degree} in recurrence equation\n\nd_k p_k(x_i) = (a_k x_i + b_k) p_k-1(x_i) + c_k p_k-2(x_i)\n\n\n\n\n\n"
},

{
    "location": "#MultivariateBases.ProbabilistsHermiteBasis",
    "page": "Introduction",
    "title": "MultivariateBases.ProbabilistsHermiteBasis",
    "category": "type",
    "text": "struct ProbabilistsHermiteBasis{P} <: AbstractHermiteBasis{P}\n    polynomials::Vector{P}\nend\n\nOrthogonal polynomial with respect to the univariate weight function w(x) = exp(-x^22) over the interval -infty infty.\n\n\n\n\n\n"
},

{
    "location": "#MultivariateBases.PhysicistsHermiteBasis",
    "page": "Introduction",
    "title": "MultivariateBases.PhysicistsHermiteBasis",
    "category": "type",
    "text": "struct PhysicistsHermiteBasis{P} <: AbstractHermiteBasis{P}\n    polynomials::Vector{P}\nend\n\nOrthogonal polynomial with respect to the univariate weight function w(x) = exp(-x^2) over the interval -infty infty.\n\n\n\n\n\n"
},

{
    "location": "#MultivariateBases.LaguerreBasis",
    "page": "Introduction",
    "title": "MultivariateBases.LaguerreBasis",
    "category": "type",
    "text": "struct LaguerreBasis{P} <: AbstractMultipleOrthogonalBasis{P}\n    polynomials::Vector{P}\nend\n\nOrthogonal polynomial with respect to the univariate weight function w(x) = exp(-x) over the interval 0 infty.\n\n\n\n\n\n"
},

{
    "location": "#MultivariateBases.AbstractGegenbauerBasis",
    "page": "Introduction",
    "title": "MultivariateBases.AbstractGegenbauerBasis",
    "category": "type",
    "text": "struct AbstractGegenbauerBasis{P} <: AbstractMultipleOrthogonalBasis{P}\n    polynomials::Vector{P}\nend\n\nOrthogonal polynomial with respect to the univariate weight function w(x) = (1 - x^2)^alpha - 12 over the interval -1 1.\n\n\n\n\n\n"
},

{
    "location": "#MultivariateBases.LegendreBasis",
    "page": "Introduction",
    "title": "MultivariateBases.LegendreBasis",
    "category": "type",
    "text": "struct LegendreBasis{P} <: AbstractGegenbauerBasis{P}\n    polynomials::Vector{P}\nend\n\nOrthogonal polynomial with respect to the univariate weight function w(x) = 1 over the interval -1 1.\n\n\n\n\n\n"
},

{
    "location": "#MultivariateBases.ChebyshevBasisFirstKind",
    "page": "Introduction",
    "title": "MultivariateBases.ChebyshevBasisFirstKind",
    "category": "type",
    "text": "struct ChebyshevBasisFirstKind{P} <: AbstractChebyshevBasis{P}\n    polynomials::Vector{P}\nend\n\nOrthogonal polynomial with respect to the univariate weight function w(x) = frac1sqrt1 - x^2 over the interval -1 1.\n\n\n\n\n\n"
},

{
    "location": "#MultivariateBases.ChebyshevBasisSecondKind",
    "page": "Introduction",
    "title": "MultivariateBases.ChebyshevBasisSecondKind",
    "category": "type",
    "text": "struct ChebyshevBasisSecondKind{P} <: AbstractChebyshevBasis{P}\n    polynomials::Vector{P}\nend\n\nOrthogonal polynomial with respect to the univariate weight function w(x) = sqrt1 - x^2 over the interval -1 1.\n\n\n\n\n\n"
},

{
    "location": "#Orthogonal-basis-1",
    "page": "Introduction",
    "title": "Orthogonal basis",
    "category": "section",
    "text": "AbstractMultipleOrthogonalBasis\nunivariate_orthogonal_basis\nreccurence_first_coef\nreccurence_second_coef\nreccurence_third_coef\nreccurence_deno_coef\nProbabilistsHermiteBasis\nPhysicistsHermiteBasis\nLaguerreBasis\nAbstractGegenbauerBasis\nLegendreBasis\nChebyshevBasisFirstKind\nChebyshevBasisSecondKind"
},

]}
